language: node_js
node_js:
    - "0.10"
    - "0.11"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
notifications:
    slack:
        rooms:
            - secure: "+jkwcQ/4YJxUzPyU6s9zD2kcoKS6T0FrgiODJszOWbIbPJvlJuY41TZg8D0nQOlsayFSZhCnWjwBER8qS14VrJHNn7YAthb4Cg2AbaNWIvT2wywTcSxqHhL86MlqLBsMa73EzpaWnbwfwsCF9T4NTuLdVnXWCHXB+4s2IzimOfk=" 
